[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  publish = "docs"
  command = "npm install pnpm && npx pnpm install && npx pnpm build"
